version: '3.8'

services:
  app:
    image: url_shortener
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
      PORT: 5000
      SERVER_TYPE: 0
      DB_TYPE: 0

      REDIS_HOST: redis
      REDIS_PORT: 6379

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  redis_data: