version: '3.8'

services:
  app:
    image: url_shortener
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
      PORT: 5000
      SERVER_TYPE: 0
      DB_TYPE: 0

      REDIS_HOST: redis
      REDIS_PORT: 7000

      DB_HOST: db
      DB_PORT: 6000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - db
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "7000:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    ports:
      - "6000:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  redis_data: