version: '3.8'

services:
  app:
    image: url_shortener
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
      PORT: 5000
      SERVER_TYPE: 0
      DB_TYPE: 0

      REDIS_HOST: redis
      REDIS_PORT: 7000
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "7000:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: