// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: pkg/proto/url_shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginUrl string `protobuf:"bytes,1,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_pkg_proto_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_pkg_proto_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *URL) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

type ShortenedURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortenedUrl string `protobuf:"bytes,1,opt,name=shortened_url,json=shortenedUrl,proto3" json:"shortened_url,omitempty"`
}

func (x *ShortenedURL) Reset() {
	*x = ShortenedURL{}
	mi := &file_pkg_proto_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenedURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenedURL) ProtoMessage() {}

func (x *ShortenedURL) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenedURL.ProtoReflect.Descriptor instead.
func (*ShortenedURL) Descriptor() ([]byte, []int) {
	return file_pkg_proto_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenedURL) GetShortenedUrl() string {
	if x != nil {
		return x.ShortenedUrl
	}
	return ""
}

var File_pkg_proto_url_shortener_proto protoreflect.FileDescriptor

var file_pkg_proto_url_shortener_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x5f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x24, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x55, 0x72, 0x6c, 0x22, 0x33, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x32, 0x57, 0x0a, 0x0c, 0x55, 0x52,
	0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x11, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x41, 0x6e, 0x64, 0x53, 0x61, 0x76, 0x65, 0x55, 0x52, 0x4c, 0x12,
	0x04, 0x2e, 0x55, 0x52, 0x4c, 0x1a, 0x0d, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x64, 0x55, 0x52, 0x4c, 0x12, 0x1d, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x0d,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x1a, 0x04, 0x2e,
	0x55, 0x52, 0x4c, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6c, 0x73, 0x65, 0x72, 0x6f, 0x6b, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_url_shortener_proto_rawDescOnce sync.Once
	file_pkg_proto_url_shortener_proto_rawDescData = file_pkg_proto_url_shortener_proto_rawDesc
)

func file_pkg_proto_url_shortener_proto_rawDescGZIP() []byte {
	file_pkg_proto_url_shortener_proto_rawDescOnce.Do(func() {
		file_pkg_proto_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_url_shortener_proto_rawDescData)
	})
	return file_pkg_proto_url_shortener_proto_rawDescData
}

var file_pkg_proto_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_url_shortener_proto_goTypes = []any{
	(*URL)(nil),          // 0: URL
	(*ShortenedURL)(nil), // 1: ShortenedURL
}
var file_pkg_proto_url_shortener_proto_depIdxs = []int32{
	0, // 0: URLShortener.ShortenAndSaveURL:input_type -> URL
	1, // 1: URLShortener.GetURL:input_type -> ShortenedURL
	1, // 2: URLShortener.ShortenAndSaveURL:output_type -> ShortenedURL
	0, // 3: URLShortener.GetURL:output_type -> URL
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_url_shortener_proto_init() }
func file_pkg_proto_url_shortener_proto_init() {
	if File_pkg_proto_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_url_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_url_shortener_proto_goTypes,
		DependencyIndexes: file_pkg_proto_url_shortener_proto_depIdxs,
		MessageInfos:      file_pkg_proto_url_shortener_proto_msgTypes,
	}.Build()
	File_pkg_proto_url_shortener_proto = out.File
	file_pkg_proto_url_shortener_proto_rawDesc = nil
	file_pkg_proto_url_shortener_proto_goTypes = nil
	file_pkg_proto_url_shortener_proto_depIdxs = nil
}
